#########################
# Batch generation
#########################
batch_generator: simple
batch_generator_validation_split: 0.1
batch_generator_batch_size: 1024
batch_generator_affinity_fraction: 0.5
max_epochs: 500
random_negative_rate: 1.0
random_negative_constant: 25
learning_rate: 0.001
patience: 5
min_delta: 0.0
loss_multiallelic_mass_spec_multiplier: 10
